### ISSUE TITLE
Update the script, plss

### ISSUE THREAD

**Issue by vurtune** [sh4dowb/whatsapp-media-decrypt#2]
@sh4dowb

**Comment by sh4dowb** [comment]
what do you need?

**Comment by rotivrotiv** [comment]
Are you able to get it to decrypt these other formats below?

application/json
application/msaccess
application/msword
application/octet-stream
application/pdf
application/rar
application/vnd.android.package-archive
application/vnd.google-earth.kml+xml
application/vnd.ms-excel
application/vnd.ms-pki.stl
application/vnd.ms-powerpoint
application/vnd.oasis.opendocument.spreadsheet
application/vnd.oasis.opendocument.text
application/vnd.openxmlformats-officedocument.presentationml.presentation
application/vnd.openxmlformats-officedocument.presentationml.template
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
application/vnd.openxmlformats-officedocument.wordprocessingml.document
application/vnd.tcpdump.pcap
application/x-7z-compressed
application/x-bittorrent
application/x-msdownload
application/x-rar-compressed
application/x-sqlite3
application/x-webarchive
application/x-zip-compressed
application/zip
audio/aac
audio/amr
audio/mp3
audio/mp4
audio/mpeg
audio/ogg; codecs=opus
image/bmp
image/gif
image/jpeg
image/png
image/vnd.dwg
image/vnd.dxf
image/webp
silenteye/tif
text/csv
text/html
text/javascript
text/plain
video/3gpp
video/avi
video/mp4
video/quicktime
video/webm

See, they were all taken from msgstore.db itself

**Comment by rotivrotiv** [comment]
> what do you need?

Are you able to get it to decrypt these other formats below?

application/json
application/msaccess
application/msword
application/octet-stream
application/pdf
application/rar
application/vnd.android.package-archive
application/vnd.google-earth.kml+xml
application/vnd.ms-excel
application/vnd.ms-pki.stl
application/vnd.ms-powerpoint
application/vnd.oasis.opendocument.spreadsheet
application/vnd.oasis.opendocument.text
application/vnd.openxmlformats-officedocument.presentationml.presentation
application/vnd.openxmlformats-officedocument.presentationml.template
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
application/vnd.openxmlformats-officedocument.wordprocessingml.document
application/vnd.tcpdump.pcap
application/x-7z-compressed
application/x-bittorrent
application/x-msdownload
application/x-rar-compressed
application/x-sqlite3
application/x-webarchive
application/x-zip-compressed
application/zip
audio/aac
audio/amr
audio/mp3
audio/mp4
audio/mpeg
audio/ogg; codecs=opus
image/bmp
image/gif
image/jpeg
image/png
image/vnd.dwg
image/vnd.dxf
image/webp
silenteye/tif
text/csv
text/html
text/javascript
text/plain
video/3gpp
video/avi
video/mp4
video/quicktime
video/webm

See, they were all taken from msgstore.db itself

**Comment by sh4dowb** [comment]
> -

"WhatsApp Document Keys" should work
you can try passing "document" for --mime
