### ISSUE TITLE
Decrypt ZIP file

### ISSUE THREAD

**Issue by mecinformatica2023** [sh4dowb/whatsapp-media-decrypt#4]
Hi,

I tested your script with JPG and it worked great. Congratulations! Now, it didn't work with ZIP files, would there be a script for ZIP files?

**Comment by sh4dowb** [comment]
`"document": b"WhatsApp Document Keys",`

try passing `-m document` as argument

**Comment by mecinformatica2023** [comment]
Hi,

Thank you for returning, but I didn't understand. I tried to do it like this, is it correct?

python decrypt.py -j "01A8496EDFEE976C7E063CCF4C96DC7DA1A11757AB85EA9DEEB6C92BBE40C8A8" -m file.enc

But I think it's wrong, because it didn't work.

Could you tell me what the syntax would be like?

**Comment by sh4dowb** [comment]
-m defines the mime/file type

python3 decrypt.py -j "key..." -m "document" file.enc

this should work

**Comment by mecinformatica2023** [comment]
Now I understand, it worked. Thanks
